/**
 * Calendar Event Types for LifeOS
 *
 * These types define the structure of calendar events in the application.
 * They are designed to be compatible with both FullCalendar and Supabase.
 */

/**
 * Event status enumeration
 */
export type EventStatus = "active" | "cancelled" | "completed";

/**
 * Database representation of a calendar event
 * This matches the structure in the Supabase 'events' table
 */
export interface LifeOSEvent {
  /**
   * Unique identifier (UUID v4)
   * Generated automatically by Supabase
   */
  id: string;

  /**
   * Event title/summary
   * Required field, max 255 characters recommended
   */
  title: string;

  /**
   * Event start date/time
   * Stored as ISO 8601 timestamp in database
   */
  start: string;

  /**
   * Event end date/time
   * Stored as ISO 8601 timestamp in database
   */
  end: string;

  /**
   * Whether this is an all-day event
   * If true, time portion of start/end is ignored by FullCalendar
   */
  all_day: boolean;

  /**
   * Optional detailed description/notes for the event
   * Can be markdown or plain text
   */
  description?: string | null;

  /**
   * Event status for filtering and display
   * Default: 'active'
   */
  status: EventStatus;

  /**
   * Background color for the event in hex format
   * Example: '#3b82f6' for blue
   */
  background_color?: string | null;

  /**
   * Border color for the event in hex format
   * If not specified, uses background_color
   */
  border_color?: string | null;

  /**
   * Text color for the event in hex format
   * Default: '#ffffff' (white)
   */
  text_color?: string | null;

  /**
   * Timestamp when the event was created
   * Auto-generated by Supabase
   */
  created_at?: string;

  /**
   * Timestamp when the event was last updated
   * Auto-updated by Supabase
   */
  updated_at?: string;

  /**
   * User ID of the event owner (for future multi-user support)
   * Currently optional, will be required when auth is implemented
   */
  user_id?: string | null;

  /**
   * Google Calendar event ID for synced events
   * NULL if the event is local-only (not synced to Google Calendar)
   * Used for 2-way sync: updates/deletes are propagated to Google
   */
  google_event_id?: string | null;

  /**
   * RRULE string (RFC 5545) for recurring events
   * Example: "FREQ=WEEKLY;BYDAY=MO,WE,FR;COUNT=10"
   * NULL for non-recurring events
   */
  recurrence?: string | null;

  /**
   * Parent recurring event ID if this is an exception
   * Links a modified/cancelled instance to its parent event
   * NULL for normal events and parent recurring events
   */
  recurrence_id?: string | null;

  /**
   * Original start time for exception instances
   * Used to identify which occurrence in the series was modified
   * NULL for normal events and parent recurring events
   */
  original_start?: string | null;
}

/**
 * Input type for creating a new event
 * Omits auto-generated fields like id, created_at, updated_at
 */
export interface CreateLifeOSEvent {
  title: string;
  start: string;
  end: string;
  all_day?: boolean;
  description?: string;
  status?: EventStatus;
  background_color?: string;
  border_color?: string;
  text_color?: string;
  user_id?: string;
  recurrence?: string | null;
  recurrence_id?: string | null;
  original_start?: string | null;
}

/**
 * Input type for updating an existing event
 * All fields are optional except id
 */
export interface UpdateLifeOSEvent {
  id: string;
  title?: string;
  start?: string;
  end?: string;
  all_day?: boolean;
  description?: string;
  status?: EventStatus;
  background_color?: string;
  border_color?: string;
  text_color?: string;
  recurrence?: string | null;
  recurrence_id?: string | null;
  original_start?: string | null;
}

/**
 * Converts a LifeOSEvent from database format to FullCalendar format
 */
export function toFullCalendarEvent(event: LifeOSEvent) {
  return {
    id: event.id,
    title: event.title,
    start: event.start,
    end: event.end,
    allDay: event.all_day,
    backgroundColor: event.background_color || "#3b82f6",
    borderColor: event.border_color || event.background_color || "#3b82f6",
    textColor: event.text_color || "#ffffff",
    extendedProps: {
      description: event.description,
      status: event.status,
      user_id: event.user_id,
      google_event_id: event.google_event_id, // Include for deduplication
    },
  };
}

/**
 * Converts FullCalendar event format to LifeOSEvent database format
 */
export function fromFullCalendarEvent(event: any): CreateLifeOSEvent {
  return {
    title: event.title || "Untitled Event",
    start: typeof event.start === "string" ? event.start : event.start.toISOString(),
    end: typeof event.end === "string" ? event.end : event.end?.toISOString() || event.start.toISOString(),
    all_day: event.allDay || false,
    description: event.extendedProps?.description,
    status: event.extendedProps?.status || "active",
    background_color: event.backgroundColor,
    border_color: event.borderColor,
    text_color: event.textColor,
  };
}
