/**
 * Task Types for LifeOS
 *
 * These types define the structure of tasks in the application.
 * They match the database schema in Supabase.
 */

/**
 * Task priority levels
 */
export type TaskPriority = "low" | "medium" | "high";

/**
 * Database representation of a task
 * This matches the structure in the Supabase 'tasks' table
 */
export interface LifeOSTask {
  /**
   * Unique identifier (UUID v4)
   * Generated automatically by Supabase
   */
  id: string;

  /**
   * Task title/description
   * Required field
   */
  title: string;

  /**
   * Whether the task is completed
   * Default: false
   */
  is_completed: boolean;

  /**
   * Task priority level
   * Default: 'medium'
   */
  priority: TaskPriority;

  /**
   * Optional due date for the task
   * Stored as ISO 8601 timestamp in database
   */
  due_date?: string | null;

  /**
   * Whether the task is urgent (Eisenhower Matrix)
   * Default: false
   */
  is_urgent?: boolean;

  /**
   * Whether the task is important (Eisenhower Matrix)
   * Default: false
   */
  is_important?: boolean;

  /**
   * User ID of the task owner (for future multi-user support)
   * Currently optional, will be required when auth is implemented
   */
  user_id?: string | null;

  /**
   * Optional goal ID to link this task to a strategic goal
   */
  goal_id?: string | null;

  /**
   * Timestamp when the task was created
   * Auto-generated by Supabase
   */
  created_at: string;

  /**
   * Timestamp when the task was last updated
   * Auto-updated by Supabase
   */
  updated_at: string;
}

/**
 * Input type for creating a new task
 * Omits auto-generated fields like id, created_at, updated_at
 */
export interface CreateTaskInput {
  title: string;
  is_completed?: boolean;
  priority?: TaskPriority;
  due_date?: string | null;
  is_urgent?: boolean;
  is_important?: boolean;
  user_id?: string | null;
  goal_id?: string | null;
}

/**
 * Input type for updating an existing task
 * All fields are optional except id
 */
export interface UpdateTaskInput {
  id: string;
  title?: string;
  is_completed?: boolean;
  priority?: TaskPriority;
  due_date?: string | null;
  is_urgent?: boolean;
  is_important?: boolean;
  goal_id?: string | null;
}

/**
 * Task filter options for querying
 */
export interface TaskFilters {
  is_completed?: boolean;
  priority?: TaskPriority;
  has_due_date?: boolean;
  overdue?: boolean;
}

/**
 * Task sort options
 */
export type TaskSortBy =
  | "created_at"
  | "updated_at"
  | "due_date"
  | "priority"
  | "title";

export type TaskSortOrder = "asc" | "desc";

/**
 * Priority color mapping for UI
 */
export const PRIORITY_COLORS: Record<TaskPriority, { bg: string; text: string; label: string }> = {
  low: {
    bg: "#10b981", // Green
    text: "#ffffff",
    label: "Low Priority",
  },
  medium: {
    bg: "#f59e0b", // Orange
    text: "#ffffff",
    label: "Medium Priority",
  },
  high: {
    bg: "#ef4444", // Red
    text: "#ffffff",
    label: "High Priority",
  },
};

/**
 * Helper function to check if a task is overdue
 */
export function isTaskOverdue(task: LifeOSTask): boolean {
  if (!task.due_date || task.is_completed) {
    return false;
  }
  return new Date(task.due_date) < new Date();
}

/**
 * Helper function to format due date for display
 */
export function formatDueDate(dueDate: string | null | undefined): string {
  if (!dueDate) return "No due date";

  const date = new Date(dueDate);
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const taskDate = new Date(date.getFullYear(), date.getMonth(), date.getDate());

  const diffTime = taskDate.getTime() - today.getTime();
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

  if (diffDays === 0) return "Today";
  if (diffDays === 1) return "Tomorrow";
  if (diffDays === -1) return "Yesterday";
  if (diffDays > 1 && diffDays <= 7) return `In ${diffDays} days`;
  if (diffDays < -1 && diffDays >= -7) return `${Math.abs(diffDays)} days ago`;

  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: date.getFullYear() !== now.getFullYear() ? 'numeric' : undefined
  });
}

/**
 * Helper function to get priority display info
 */
export function getPriorityInfo(priority: TaskPriority) {
  return PRIORITY_COLORS[priority];
}
